# Generated by Django 5.1.7 on 2025-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_postjobmodel_company_postjobmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobmodel',
            name='application_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='postjobmodel',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
