# Generated by Django 5.1.7 on 2025-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('job-seeker', 'Job Seeker'), ('employer', 'Employer')], default='job-seeker', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
